server:
  port: 8070

internal:
  api-key: ${INTERNAL_API_KEY}

rabbitmq:
  queue:
    name: message_queue
  queue_with_delay:
    name: delay_queue
  user_check_queue:
    name: user_check_queue

spring:
  application:
    name: WorkoutManager
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    #By default, ??
    username: guest
    password: guest
    host: localhost
    port: 5672

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        ##Test update